Мазырина Алена - Этап 1
naumen-student/naumen.scala.practice.2022.spring pull request #2
Opened 2022-05-12 16:32 UTC by alenmaz

2022-05-14 11:05 UTC, DenginRoman requested changes
1.
Многие функции, работающие со фьючами, возвращают фьючи, а преобразования описаны с помощью map, flatMap - круто! Применили асинхронный подход! Но некоторые функции асинхронный код превращают в синхронный через `Await.result`, что сводит на нет все плюсы асинхронного кода и усилия, потраченные на его написание. Нужно везде сохранить асинхронность. Я комменты на каждом месте не оставлял, но их легко найти по `Await.result`

2.
Парсинг Json'ов кажется громоздким и его можно упростить. Достаточно описать модели данных, которые приходят из вне, описать для них ридеры, а дальше json парсить сразу в модель с помощью `json.asOpt[JobDTO]`. При этом парсинг стоит проводить максимально близко к точки приёма данных из внешнего источника, чтобы после этого быть уверенным, что мы работает с конкретными типами и валидными данными.

3.
Модели для БД и внешнего взаимодействия стоит разделять. Это способствует более лёгкой поддержки приложения в будущем

2022-05-14 11:05 UTC, DenginRoman commented on app/controllers/JobAggregatorController.scala
> +          Try(Await.result(jobAggregatorService.processJobResponse(jobAggregatorService.buildJobRequest(tag, area)), Duration.Inf)) match {
Преобразование асинхронного кода в синхронный с помощью `Await.result` и тем самым блокировка исходного потока. Т.е. исходный поток будет вынужден ждать, пока завершится запрос к БД,(а выставляя таймаут `Duratino.Inf` есть вероятность ждать бесконечно) вместо того, чтобы выполнять какую-то полезную нагрузку. А у слика для работы с БД пул потоков  отдельный.

Если `Await.result` тут использовался для того, чтобы развернуть результат фьючи для помещения его в `Try`, то лучше использовать стандартные комбинаторы монады (`map`, `flatMap`, ...) или специальные комбинаторы фьючи (`transform`, `recover`, ...)

Если же `Await.restul` использовался из-за того, что Action требует `Result`, а не фьючу, то стоит использовать асинхронный вариант `Action.async`, который ждет функцию, возвращающую фьючу:

```scala
def loadJobs(tag: Option[String], area: Option[String]) = Action.async { implicit request => Future(Ok("ok")) }
```

Ну и везде, где используется `Await.result` его следует убрать, заменяя раскрытие монады `Future` и манипуляции с полученным значением на цепочки мандных комбинаторов, описывающих преобразование данных. Во-первых это более ФП подход, а во-вторых более эффективный с точки зрения производительности и использования ресурсов.

2022-05-14 11:05 UTC, DenginRoman commented on app/controllers/JobAggregatorController.scala
> +              case None => print("Couldn't get list of jobs")
Логгирование следует осуществлять специальными средствами (например, `play.api.Logger`), которые:
1. умеют присваивать уровень критичности сообщениям
2. инкапсулируя в себе логику вывода сообщения могут гибко настраиваться - в каком формате вывести сообщения (например, можно к сообщению добавить время, не меняя исходный код, а меняя только конфиг), куда вывести (файл/экран/общее хранилище логгов) и т.п.

Обычные print'ы же достаточно сложно потом будет сопровождать, если будет необхдимо как-то изменить логику логгирования

2022-05-14 11:05 UTC, DenginRoman commented on app/controllers/JobAggregatorController.scala
> +            case Failure(_) => print("Failed job response processing")
В сообщения об ошибках лучше добавлять подробности, т.к. сообщения вида "что-то пошло не так" не дают информации для решения проблемы:

```scala
case Failure(e) => print(s"Failed job response processing: ${e.getMessage}")
```

2022-05-14 11:05 UTC, DenginRoman commented on app/model/Area.scala
> +case class Area(id: String, name: String, children: Option[JsValue])
В данном кейсклассе смешиваются распарсенные данные (id, name) и нераспарсенные, но представляющие собой какую-то структуру, описанную в api. Такое совмещение усложнит работу с полученными данными.

Обычно при работе с данными, полученными из внешней среды, стараются распарсить их как можно раньше при получении, чтобы потом иметь возможность работать с проверенными, типизированными моделями. Т.е. можно описать 2 кейс класса, для каждого из которых описать ридеры:

```scala
case class Area(id: String, name: String, children: Option[Seq[child]])

case class Child(<поля дочернего элемента>)

object Area {
  implicit val areaReads: Reads[Area] = Json.reads[Area] //кстати, для парсинга простых данных и составленных из них кейс классов можно использовать стандартный ридер
}

object Child {
  implicit val childReads: Reads[Child] = Json.reads[Child]
}
```

2022-05-14 11:05 UTC, DenginRoman commented on app/model/JobRequest.scala
> +case class JobRequest(jobid: String, city: String, keyword: String)
составные слова лучше писать используя визуальные разделения слов: `camelCase`'ом или `snake_case` 'ом, но единообразно

2022-05-14 11:05 UTC, DenginRoman commented on app/schedulers/JobAggregatorScheduler.scala
> +  val frequency = configuration.get[Int]("request.frequency")
здесь и далее при чтении конфига: а что будет, если в конфиге нет параметра по пути request.frequency? Возможно 2 вида поведения:
1. упасть с ошибкой инициализации (для этого сообщение должно быть понятным где и что пошло не так);
2. подставить значение по умолчанию (в этом случае должен лететь заметный warning, что используется значение по умолчанию)

2022-05-14 11:05 UTC, DenginRoman commented on app/schedulers/SchedulerActor.scala
> +          case Failure(_) => print("Failed job response processing\n")
неинформативное сообщение об ошибке

2022-05-14 11:05 UTC, DenginRoman commented on app/schedulers/SchedulerActor.scala
> +        Try(Await.result(jobAggregatorService.processJobResponse(jobAggregatorService.buildJobRequest(Some(pair._1), Some(pair._2))), Duration.Inf)) match {
здесь и далее в этом методе: `Await.result` ухудшает производительность и использование ресурсов

2022-05-14 11:05 UTC, DenginRoman commented on app/service/JobAggregatorService.scala
> +    def addJobs(jobs: Seq[Job], area: String, keyword: String): Seq[Future[Unit]] = {
Future не ленивая. Она является запущенной, как только появилась на свет. Соответственно, если у нас есть список фьюч, они выполняются все одновременно (в рамках возможностей своего пула потоков). Если их будет очень много и они будут работать долго, мы забьем пул и другие задачи выполняться не будут, пока не разгребутся все фьючи.

Тут можно использовать 2 подхода:
1. формирование цепочки фьюч, которые выполняются последовательно друг за другом. Схемотично это выглядит так:

```scala
  jobs => addJob(jobs[0], area, keyword).flatMap(addJob(jobs[1], area, keyword)).flatMap(addJob(jobs[2], area, keyword))
```

только строить эту цепочку нужно будет средствами языка, например через `foldLeft`.

 При этом подходе мы теряем возможность их параллельного исполнения, но гарантируем большую безопасноть с точки зрения неконтролируемого использования ресурсов

2. использовать инструменты контролируемого параллельного запуска, которые не сразу весь набор фьюч параллельно запускают (первое, что в голову пришло Akka streams и его mapAsync, примеры которого можно посмотреть тут https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/mapAsync.html)

Тут сейчас достаточно будет варианта 1., вариант 2 привел больше для общего развития )

2022-05-14 11:05 UTC, DenginRoman commented on app/service/JobAggregatorService.scala
> +        var req = ws.url("https://api.hh.ru/vacancies")
Явно не ФП подход, но его можно легко преобразовать в ФП :) Для этого достаточно последовательно вызывать методы обновления состояния:

```scala
val req = ws.url("https://api.hh.ru/vacancies")
  .addQueryStringParameters {
    tag match ...
  }
  .addQueryStringParameters {
    area match ...
  }
req

2022-05-14 11:05 UTC, DenginRoman commented on app/service/JobAggregatorService.scala
> +                    case _ => print("Parsing of jobs failed!\n")
тут можно вывести, например, тело json'а (при наличии), чтобы в случае неудачи из логов можно было понять почему парсинг завершился неудачей

2022-05-14 11:05 UTC, DenginRoman commented on app/service/JobAggregatorService.scala
> +    {
В Scala открывающиеся скобки идут на одной строке с описанием функции ) А вообще вне зависимости от языка важно использовать единый стиль оформления

2022-05-14 11:05 UTC, DenginRoman commented on app/service/JobAggregatorService.scala
> +    def parseRegions(regionJson: JsValue): Option[List[Area]] = {
Кажется этот парсинг можно заменить обычным наличием `Reader'ов` у класса модели данных внешнего сервиса

2022-05-14 11:05 UTC, DenginRoman commented on app/model/Job.scala
> +case class Job(id: String, title: String, requirements: String, responsibility: String, salaryFrom: Int, salaryTo: Int, salaryCurr: String, url: String)
В общем случае модель данных для БД и модель данных, описывающую приходящие из внешнего сервиса данные, следует разделять, потому что с течением времени и с внешним сервисом и с БД могут происходить независимые изменения (Например, может смениться api внешнего сервиса или из-за необходимости оптимизаций придется пересмотреть структуру БД). При разных моделях поддерживать изменения будет проще.

Т.е. лучше описать 2 класса:

```scala
JobDTO(<поля>) // DTO - Data Transfer Object - данные, получаемые из внешнего сервиса
Job(<поля>) //модель для БД
```

2022-05-14 11:05 UTC, DenginRoman commented on app/model/Job.scala
> +      ((JsPath \ "salary" \ "to").read[Int] or Reads.pure(0)) and
А точно ли нужны деволтные значения 0? Может, если данных нет (null) их и следует оставлять пустыми? Т.е. сделать тип `Option[Int]`

2022-05-14 11:05 UTC, DenginRoman commented on app/model/Job.scala
> +      ((JsPath \ "salary" \ "to").read[Int] or Reads.pure(0)) and
А точно ли нужны деволтные значения

2022-05-14 11:05 UTC, DenginRoman commented on app/model/db/JobRequestTable.scala
> +  def keyword = column[String]("keyword")
составные слова написаны слитно и не понято

2022-05-14 11:05 UTC, DenginRoman commented on app/model/db/JobTable.scala
> +    def url = column[String]("url")
составные слова написаны слитно и не понятно

2022-05-14 11:05 UTC, DenginRoman commented on app/service/JobAggregatorService.scala
> +    def processJobResponse(request: WSRequest): Future[Option[List[Job]]] = {
кажется такой парсинг можно упростить, описав соответствующие модели и определив для них ридеры

2022-05-14 11:05 UTC, DenginRoman commented on conf/evolutions/default/1.sql
> +)
слитно написанные составные слова

2022-05-15 16:14 UTC, alenmaz commented on app/controllers/JobAggregatorController.scala
> +          Try(Await.result(jobAggregatorService.processJobResponse(jobAggregatorService.buildJobRequest(tag, area)), Duration.Inf)) match {
![image](https://user-images.githubusercontent.com/74190014/168481822-86cf3d85-a53c-4228-a616-760d8044692d.png)
Мне не очень понятно, как можно было бы избавиться от Await.Result здесь. Если не дожидаться завершения всех фьюч, приложение заканчивает работу раньше, чем они все добавятся в БД, и в итоге в БД данные не добавляются.

![image](https://user-images.githubusercontent.com/74190014/168482343-d8d08821-528f-484d-b321-f1b21bbe9520.png)
![image](https://user-images.githubusercontent.com/74190014/168482754-cdf5242c-e49d-4d2d-8495-296a7a7abcbf.png)

Аналогично возникла проблема при переписывании request'а - нужно дождаться списка Area, чтобы вытащить оттуда айдишник.

2022-05-16 12:05 UTC, DenginRoman commented on app/controllers/JobAggregatorController.scala
> +          Try(Await.result(jobAggregatorService.processJobResponse(jobAggregatorService.buildJobRequest(tag, area)), Duration.Inf)) match {
Немного оффтопик

Исходный код в комментариях можно раскрашивать в соответствии с синтаксисом скалы (или в соответствии с другим языком) :)  Для этого нужно указать что за язык в блоке кода используется:

Следующий блок

\```scala
def someAction(x: Foo): Bar  = ???
\```

превратится в раскрашенный код:

```scala
def someAction(x: Foo): Bar  = ???
```
**1. По поводу первого блока `loadJobs`:**
Если абстрагировано взглянуть на действия 
```scala
  Await.result(jobAggregatorService.addJobs(value, area, keyword), Duration.Inf)
  Future(Ok(s"Loading of jobs with tags (${keyword.getOrElse("Empty")}, ${area.getOrElse("Empty")}) done"))
```
можно увидеть, что мы сначала разворачиваем монаду и достаем значение, а потом заворачиваем в монаду другое значение. По аналогии с `Option` это выглядело бы так:
```scala
  jobAggregatorService.addJobs(value, area, keyword).get
  Option((Ok(s"Loading of jobs with tags (${keyword.getOrElse("Empty")}, ${area.getOrElse("Empty")}) done"))
```
Здесь можно применить стандартные комбинаторы монады, которые описывают преобразование данных без раскрытия монады. Т.е. `map` и `flatMap`. Для `Future` эти комбинаторы опишут последовательное выполнение. Т.е. то, что внутри `map` будет выполняться только после того, как завершаться действия исходной фьючи. НО в отличии от `Await.result` мы уже не будет заставлять основной поток ждать окончания работы этой фьючи. Основной поток сконструировал нам фьючу, описанную цепочкой `map`'ов , `flatMap`'ов и запустил её (возможно в другом контексте) и пошел выполнять другую полезную работу.

**2. блок `buildJobRequest`**
Если мы хотим, чтобы наш код был асинхронным, нам придется пробрасывать асинхронность (фьючи) по всему стеку вызову. Т.е. если у нас в функции вызывается какая-то функция тип результата которой фьюча, то и тип результата нашей функции должен быть фьюча. Без этого асинхронность нарушится. Т.е. тут можно тип результата функции `buildJobRequest` сделать не `WSRequest`, а `Future[WSRequest]`. При этом нам сначала придется вычислить зависимую фьючу `getAreaId` и через map/flatMap сконструировать фьючу с внутрянкой WSRequst на основе areaId и вернуть её в качестве результата

НО
Исходя из названия и применения эта функция просто конструирует WSRequest и никаких внешний доп. действий (ходить во внешний сервис) не должна. Поэтому можно немного изменить сигнатуру и в качестве аргумента принимать не area, а areaId. А вот вычислять areaId по area (ходить во внешний сервис за ним) уже в том методе, где будет вызываться buildJobRequest и выполняться ws.get.

2022-05-16 14:20 UTC, DenginRoman commented
@alenmaz , я сейчас только заметил, что в коде несколько раз встречается генерация значения `null`. Это опасно, т.к. наличие null хотя бы в одном месте программы заставляет проверять на null всё. Без проверок есть риск наткнутся на необработанное исключение NullPointerExecption. Если где-то требуется описание отсутствия чего-то, стоит использовать значение `None` монады `Option` и работать с ним с помощью map'ов flatMap'ов. Это безопаснее и надежнее, т.к. на уровне типа мы видим что есть возможность отсутствия значения и соответствующим образом обработаем.

2022-05-30 12:08 UTC, DenginRoman requested changes
Супер! Получилось перейти на асинхронный подход! Очень круто, что нигде нет выброса исключения и идет работа с мондами через комбинаторы / паттерн матчинг! Истинный ФП стиль :)

Однако, ряд вещей стоит поправить. Наиболее важный - неконтролируемый параллельный запуск фьюч `Future.traverse`. Остальные замечания уже больше рекомендации, полезные для дальнейшего поддержания и кода

2022-05-30 12:08 UTC, DenginRoman commented on app/controllers/JobAggregatorController.scala
> +          case Some(value) => jobAggregatorService.addJobs(value.map(dto => dto : Job), area, keyword).flatMap(_ => Future(Ok(s"Loading of jobs with tags (${keyword.getOrElse("Empty")}, ${area.getOrE
`Future.flatMap(x => Future(Ok(x))` то же самое, что и `Future.map(x => Ok(x))` только менее многословно ;)

2022-05-30 12:08 UTC, DenginRoman commented on app/model/Job.scala
> +                  url: String)
поехали отступы, минор

2022-05-30 12:08 UTC, DenginRoman commented on app/model/Job.scala
> +               url: String)
снова отступы, минор

2022-05-30 12:08 UTC, DenginRoman commented on app/model/Job.scala
> +  implicit  def jobToJobDTO(job: Job): JobDTO = JobDTO(
Вот насчет имплиситного преобразования Job в JobDTO я бы задумался. Неявные манипуляции без особой причины усложняют чтение кода. И кстати, зачем надо уметь Job приводить к JobDTO (модель из БД к модели из стороннего сервера, на который мы ничего не шлем, а наоборот из него читаем и кладем в БД)

2022-05-30 12:08 UTC, DenginRoman commented on app/model/Job.scala
> +  implicit def jobDTOtoJob(jobDTO: JobDTO): Job = Job(
аналогично имплиситное преобразование, точно ли нужно?

2022-05-30 12:08 UTC, DenginRoman commented on app/schedulers/JobAggregatorScheduler.scala
> +        5
"магические" числа лучше выносить в именованные константы

2022-05-30 12:08 UTC, DenginRoman commented on app/schedulers/SchedulerActor.scala
> +  val logger = Logger("debug")
Логгеры обычно называют по имени модуля, действия которого они логгируют, так проще будет отыскать в огромной массе текста нужную информацию

2022-05-30 12:08 UTC, DenginRoman commented on app/schedulers/SchedulerActor.scala
> +              Future()
Посто Future? Без всего? Если нужен тип `Future[Unit]`, то есть спец метод `Future.unit`

2022-05-30 12:08 UTC, DenginRoman commented on app/service/JobAggregatorService.scala
> +        Future.traverse(jobs)(job => addJob(job, area, keyword))
Если это была попытка избавиться от запуска всего списка задач параллельно, то `Future.traverse` наоборот параллельно запускает задачи. Разве что тип результата теперь другой. Чтобы описать последовательный запуск фьюч, придется использовать комбинаторы flatMap

2022-05-30 12:08 UTC, DenginRoman commented on app/service/JobRequestService.scala
> +  def getAreaId(name: Option[String]): Future[Option[String]] = {
Большая вложенность паттерн матчинга, она точно нужна? Если да, возможно стоит внутрянку вынести в отдельный метод

2022-05-30 12:08 UTC, DenginRoman commented on app/schedulers/JobAggregatorScheduler.scala
> +  if(doRun.getOrElse {
Начиная с этого момента используется getOrElse для применения значения по умолчанию при отсутствии параметра  в конфиге. Лучше тогда применить это в сам момент чтения параметра и типы сделать не Option[Boolean], а просто Boolean (ну и с другими параметрами тоже), чтобы применение значения по умолчанию было в одном единственном месте максимально близко к получению значения

2025-06-23 15:17 UTC, closed without merging